// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zznubsevogfqoxgkdnzg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6bnVic2V2b2dmcW94Z2tkbnpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5MDIxNjIsImV4cCI6MjA3NDQ3ODE2Mn0.wm79eU6XlH-gniv6YYpkFTR9WVtw2vmgQbbmLOm9HT8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});